### ISSUE TITLE
The 'argv' option is not supported when spawning Android apps

### ISSUE THREAD

**Issue by fdciabdul** [httptoolkit/frida-js#1]
after successfully connected to frida-server in android , then when i try to call `spawnWithScript`

then this happen 

```bash
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
[ "The 'argv' option is not supported when spawning Android apps" ]

Node.js v21.1.0
```

sample code : 

```javascript

import { connect } from 'frida-js';

const fridaClient = await connect({
    host :"192.168.144.203:27042"});

    await fridaClient.spawnWithScript(
        'frida',
        ['-U -l bypass.js -f com.example.app'],
        `
            const targetFn = DebugSymbol.fromName('a_target_function');
    
            // Hook the target function and replace the argument
            Interceptor.attach(ptr(targetFn.address), {
                onEnter(args) {
                    // Modify your target functions args
                },
                onLeave(retval) {
                    // Or return value
                }
            });
        `
    );
    
    ```

**Comment by pimterry** [comment]
I think you've misunderstood how this works - you're trying to pass arguments to the Frida CLI client, to tell it how to control the server for you.

By using this library, you don't need to use the CLI client - instead you're sending commands to the server on the phone directly.

You probably want to do something like this:

```javascript
await fridaClient.spawnWithScript(
    'com.example.app', // Name of the app
    undefined, // Must be undefined on Android
    contentsOfBypassJsScript // The script to run, as a string
);
```

I.e. you'll need to read the contents of bypass.js, or put that script (as a string) in here directly as the 3rd argument.

That does effectively the same thing as the command you want to run with the Frida CLI (`frida -U -l bypass.js -f com.example.app`) but with no CLI required.

Does that make sense?
