### ISSUE TITLE
A way to listen to the agent messages

### ISSUE THREAD

**Issue by Patrick-van-Halm** [httptoolkit/frida-js#3]
An enhancement of this system would be to be able to listen to the agent messages. Since Frida has the ability to send and receive messages from scripts. This could be handy for when certain commands need to be executed or an unhook functionality needs to be called. 

The implementation of this is within the RPC system of Frida: [RPC.vala](https://github.com/frida/frida-core/blob/main/lib/base/rpc.vala) and in Frida-node in [Script.ts](https://github.com/frida/frida-node/blob/main/lib/script.ts)

**Comment by pimterry** [comment]
Sounds like a great idea. Would you be interested in opening a PR?

**Comment by Patrick-van-Halm** [comment]
> Sounds like a great idea. Would you be interested in opening a PR?

I've tried looking into the how but I unfortunately have too little experience with the DBus system and so I might take a crack at it at a later date or if someone knows how to easily implement it can do it before me.

**Comment by Patrick-van-Halm** [comment]
Couldn't lay it to rest and got it implemented haha
